[simulation]
	name = "goals"
	fastmode = false
	[[simulation.robot]]
		file = "atrv_with_ir"
		name = "our_robot"
	[[simulation.camera_position]]
		robot = "our_robot"
		x_cam = 0.5
		y_cam = 0
		z_cam = 0.6
		p_cam = 0
		q_cam = 0
		r_cam = 3.14
